=== RamonIglesiasPardo/producto1/DocTypeDefinition.dtd
<!ELEMENT contenido (temaNivel1|FeedRSS)+>
<!ATTLIST contenido
  xmlns CDATA #FIXED ""
  titulo CDATA #REQUIRED>

<!ELEMENT temaNivel1 (temaNivel2|texto|video)+>
<!ATTLIST temaNivel1
  xmlns CDATA #FIXED ""
  titulo CDATA #REQUIRED>

<!ELEMENT temaNivel2 (temaNivel3|texto|video)+>
<!ATTLIST temaNivel2
  xmlns CDATA #FIXED ""
  titulo CDATA #REQUIRED>

<!ELEMENT temaNivel3 (temaNivel4|texto|video)+>
<!ATTLIST temaNivel3
  xmlns CDATA #FIXED ""
  titulo CDATA #REQUIRED>

<!ELEMENT temaNivel4 (texto|video)+>
<!ATTLIST temaNivel4
  xmlns CDATA #FIXED ""
  titulo CDATA #REQUIRED>

<!ELEMENT texto (#PCDATA|imagen)*>
<!ATTLIST texto
  xmlns CDATA #FIXED "">

<!ELEMENT video (#PCDATA)>
<!ATTLIST video
  xmlns CDATA #FIXED "">

<!ELEMENT FeedRSS (item)+>
<!ATTLIST FeedRSS 
  tituloCanal CDATA #REQUIRED
  web CDATA #REQUIRED
  descripcion CDATA #REQUIRED
  idioma CDATA #REQUIRED
  copyright CDATA #REQUIRED
  fecha CDATA #REQUIRED
  xmlns CDATA #FIXED ""
  >

<!ELEMENT item (title|link|description|pubDate|author|category)+>
<!ATTLIST item
  xmlns CDATA #FIXED "">

<!ELEMENT title (#PCDATA)>
<!ATTLIST title
  xmlns CDATA #FIXED "">

<!ELEMENT link (#PCDATA)>
<!ATTLIST link
  xmlns CDATA #FIXED "">

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
  xmlns CDATA #FIXED "">

<!ELEMENT pubDate (#PCDATA)>
<!ATTLIST pubDate
  xmlns CDATA #FIXED "">

<!ELEMENT author (#PCDATA)>
<!ATTLIST author
  xmlns CDATA #FIXED "">

<!ELEMENT category (#PCDATA)>
<!ATTLIST category
  xmlns CDATA #FIXED "">

<!ELEMENT imagen (#PCDATA)>
<!ATTLIST imagen
  xmlns CDATA #FIXED "">

=== RamonIglesiasPardo/producto1/XMLBase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<?xml-stylesheet type="text/xsl" href="XMLaHTML.xsl"?> llamada al XSLT DTD-->
<!DOCTYPE contenido SYSTEM "DocTypeDefinition.dtd">

<contenido titulo="Proyecto: Learning XML">

  <temaNivel1 titulo="1. Lenguajes de marcas">

    <temaNivel2 titulo="1.a. ¿Qué son los lenguajes de marcas? ">

      <texto>
        Son un método de codificación de documentos que además del texto incluyen etiquetas o marcas que contienen información adicional acerca de la estructura del texto, su contenido semántico o cualquier otra información lingüística o extralingüística. En definitiva se podría definir como el lenguaje en que se escribe el texto para que el ordenador pueda manipularlo.
        La mayoría de los lenguajes de marcas son legibles, pues dichas anotaciones pueden distinguirse del texto. Por ejemplo encontramos las etiquetas de formato “&lt;” y “&gt;” en HTML, xHTML y XML y sabemos que lo que hay dentro de estos delimitadores es el lenguaje de marcado, y que el resto del texto es simplemente el texto anotado.
        También consideramos importante destacar que los lenguajes de programación no son lo mismo que los lenguajes de marcas, ya que el lenguaje de marcado no tiene funciones aritméticas o variables.

        Las características más relevantes de los lenguajes de marca son:
        Utilizan texto plano: pueden ser editados con cualquier procesador de textos y son independientes de la plataforma.
        Son compactos: las marcas se combinan con el contenido.
        Tienen facilidad de procesamiento: Por lo general resultan lenguajes fáciles de comprender y aprender.
        Presentan una gran flexibilidad: Se pueden usar en cualquier área.

        Los lenguajes de marca se pueden clasificar en dos grandes grupos:
        Lenguajes de presentación y lenguajes de procedimiento: Se utilizan para definir el formato y la presentación del texto. Por tanto, este tipo de marcado es útil para maquetar la presentación de un documento (por ejemplo la fuente del texto o la aparición de saltos de página) y el programa debe interpretar el código con el mismo orden en que aparece.
        Lenguajes descriptivos o semánticos: Definen el significado de los fragmentos de texto mediante las marcas, sin detallar cómo serán representados ni en qué orden. Los fragmentos se etiquetan tal como son y no tal como deben aparecer. Por ejemplo, definen el texto de un hipervínculo para que cuando el usuario pulse sobre este texto produzca la acción de llevarle a una página determinada.
      </texto>

    </temaNivel2>
    <temaNivel2 titulo="1.b. Ejemplos de lenguajes de marcas ">

      <texto>
        GML (Generalized Markup Language):
        Este lenguaje descriptivo se utiliza para definir el tipo de texto (si se trata de un párrafo, cabecera, lista, tabla...). El documento puede tener diferentes perfiles y puede cambiar de un tipo de perfil a otro. Por ejemplo, es posible dar formato a un documento para impresora láser simplemente especificando un perfil para el dispositivo en cuestión sin modificar el documento en sí.

        SGML (Standard Generalized Markup Language):
        El desarrollo de GML cambió al SGML que es un estándar para definir lenguajes de marcas generales para documentos descendiente del GML.

        XML (Extensible Markup Language):
        Fue inicialmente un simplificado desarrollo de SGML que ha recibido una gran aceptación. Más adelante explicaremos de qué se trata.

        HTML (HyperText Markup Language):
        Es un lenguaje de marcado de presentación ampliamente utilizado para definir el contenido de una página web (maquetación y estructuración). Al ser un estándar, HTML permite que cualquier web escrita en una determinada versión pueda ser interpretada de la misma forma por cualquier navegador web actualizado.

        xHTML (eXtensible HyperText Markup Language):
        Podríamos definirlo como HTML expresado como XML válido. Lo estudiaremos más detalladamente a lo largo del presente trabajo.

        Hay muchos más lenguajes de marcado, como por ejemplo: RTF (lenguaje de presentación), TeX (lenguaje de procedimiento),YAML (lenguaje descriptivo).
      </texto>

    </temaNivel2>
  </temaNivel1>
  <temaNivel1 titulo="2. Extensible Markup language (XML) ">

    <temaNivel2 titulo="2.a. Definición de XML">

      <texto>
        El XML es un lenguaje de adaptación del SGML (Standard Generalized Markup), es un lenguaje que permite el etiquetado y organización de documentos. Así pues, XML no es un lenguaje como tal, sino más bien un sistema que permite definir los lenguajes. Como ejemplo de algunos lenguajes que el XML puede definir podemos encontrarnos con el SVG, o el XHTML.

        El metalenguaje aparece como un standard que estructura el intercambio de información entre las diferentes plataformas. Las hojas de cálculo, los documentos de textos, o incluso las páginas web, son algunos de los campos donde se utiliza el lenguaje XML.

        Las ventajas que derivan de la utilización del XML podrían ser como por ejemplo su extensibilidad, ya que permite añadir nuevas etiquetas tras el diseño del documento; su analizador es standard, no requiere de cambios para cada metalenguaje que se desea utilizar; y quizá como más importante o llamativo, es que facilita el análisis y el procesamiento de los documentos XML creados por terceros.

        El XML presenta una serie de ventajas muy atractivas para los desarrolladores, especialmente porque permite relacionar aplicaciones de diferentes lenguajes e incluso plataformas. El XML busca una universalidad de los lenguajes de desarrollo.

        Nos encontramos con lenguajes creados con XML, como ejemplos podríamos nombrar el XSL (Extensible Stylesheet Languaje) o el XLINK.
      </texto>

    </temaNivel2>
    <temaNivel2 titulo="2.b. Utilidades de XML">

      <texto>
        Debemos partir de la idea que el XML no es un lenguaje de programación sino de marcado. Así pues, podemos decir que es un sistema que ofrece la posibilidad de estructurar y representar datos. Debemos observarlo como una herramienta. Actualmente es muy común que los programas incluyen archivos de configuración en XML. Podríamos citar aplicaciones de Microsoft del tipo .NET, o incluso en Apache.

        Si tratáramos de desarrollar un programa con interfaz gráfica sería necesario organizar todas las imágenes de manera que vayan cargando a medida que se necesitaran. Aquí, el XML es de gran ayuda puesto que permite agruparlas, etiquetarlas, especificar su ubicación, relacionarlas con otros datos, todo a preferencia de los mismos diseñadores.

        Pero el XML no sólo sirve como una herramienta de organización de recursos y configuración de programas. También cumple un papel muy importante, quizás su punto más fuerte o relevante. La posibilidad de comunicación con otras aplicaciones de diferentes plataformas y sin importar el origen de la información. Sirva como ejemplo que se podría tener un programa en ejecución en Windows con una base de datos de SQL Server, e inclusive tener en Linux uno con Oracle, compartiendo ambos datos gracias a una estructura en XML.

        Con toda seguridad en los servicios web son componentes de la red que brindan la posibilidad de realizar una serie variada de operaciones. Gracias al XML, se pueden comunicar sin importar el tipo de plataforma, cualquiera puede hacer uso de sus ventajas.

        Quizá habría que resaltar que es una herramienta de escasa complejidad, es fácil de usar e innegablemente útil.
      </texto>

    </temaNivel2>
    <temaNivel2 titulo="2.c. Estructura de documentos XML ">

      <texto>
        Estructura genérica XML:

        &lt;raíz&gt;
        &lt;hijo1&gt;
        &lt;subhijo1_1&gt;
        &lt;subhijo1_1_1&gt; ... &lt;/subhijo1_1_1&gt;
        &lt;subhijo1_1_2&gt; ... &lt;/subhijo1_1_2&gt;
        ...
        &lt;/subhijo1_1&gt;
        &lt;subhijo1_2&gt; ... &lt;/subhijo1_2&gt;
        ...
        &lt;/hijo1&gt;
        &lt;hijo2&gt; ... &lt;/hijo2&gt;
        ...
        &lt;/raíz&gt;

        Estructura documento XML con prólogo:

        &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        &lt;nota&gt;
        &lt;para&gt;Pedro&lt;/para&gt;
        &lt;de&gt;Laura&lt;/de&gt;
        &lt;titulo&gt;Recordatorio&lt;/titulo&gt;
        &lt;contenido&gt;El jueves es mi cumpleaños&lt;/contenido&gt;
        &lt;/nota&gt;

        Los documentos XML tienen una estructura general que está formada en dos partes:

        -Prólogo, aunque opcional, contiene una secuencia de instrucciones de procesamiento y/o declaración del tipo de documento. Se puede dividir en dos partes:

        Declaración XML. Establece la versión de XML, el tipo de codificación y si es un documento autónomo.

        En la declaración XML nos encontramos que es una instrucción de procesamiento especial, y que cumple diferentes funciones:

        -Marca el documento como texto XML
        -Incluye la declaración de la versión de XML utilizada en el documento
        -Aporta información sobre la codificación empleada para representar los caracteres
        -Indica si el documento es autónomo o no.

        Si observamos este ejemplo:

        &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot; standalone=&quot;yes&quot;?&gt;

        Nos encontramos con que nos indica que es un documento XML, y  que la versión XML es la 1.0.
        Con la información “encoding=ISO-8859-1” nos informa que el lenguaje es el asociado a los países de la Europa Occidental, permite acentos y es el usado en castellano. Cómo información general hay que indicar que por defecto el encoding sería “UTF-8”, pero no admite caracteres ni acentos usados en el castellano.
